-- EvoMind server schema (MySQL 8)
CREATE TABLE IF NOT EXISTS user_account (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  phone VARCHAR(32) UNIQUE,
  wechat_openid VARCHAR(128) UNIQUE,
  nickname VARCHAR(64) NOT NULL,
  avatar_url VARCHAR(512),
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plan_catalog (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(32) UNIQUE NOT NULL,
  name VARCHAR(32) NOT NULL,
  period ENUM('WEEK','MONTH') NOT NULL,
  feature_json JSON NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscription_order (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_no VARCHAR(64) UNIQUE NOT NULL,
  user_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  channel ENUM('WECHAT','ALIPAY') NOT NULL,
  compute_cost DECIMAL(10,2) NOT NULL,
  final_amount DECIMAL(10,2) NOT NULL,
  status ENUM('INIT','PAID','FAILED','REFUNDED') NOT NULL DEFAULT 'INIT',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  paid_at TIMESTAMP NULL,
  INDEX idx_user(user_id)
);

CREATE TABLE IF NOT EXISTS compute_meter_rule (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  metric_code VARCHAR(64) UNIQUE NOT NULL,
  metric_name VARCHAR(64) NOT NULL,
  unit_price DECIMAL(10,4) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS compute_usage_fact (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  stat_date DATE NOT NULL,
  metric_code VARCHAR(64) NOT NULL,
  usage_value DECIMAL(12,4) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_usage(user_id, stat_date, metric_code)
);

CREATE TABLE IF NOT EXISTS compute_cost_snapshot (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  period ENUM('WEEK','MONTH') NOT NULL,
  raw_cost DECIMAL(10,2) NOT NULL,
  rounded_cost DECIMAL(10,2) NOT NULL,
  subscription_fee DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_period(user_id, period)
);

CREATE TABLE IF NOT EXISTS ai_call_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT,
  scene_code VARCHAR(64) NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  token_in INT DEFAULT 0,
  token_out INT DEFAULT 0,
  latency_ms INT DEFAULT 0,
  cost_amount DECIMAL(10,4) DEFAULT 0,
  success TINYINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
